### ISSUE TITLE
[Other]: Please clarify the License compiled with this project

### ISSUE THREAD

**Issue by trevorwang** [openimsdk/protocol#28]
### What would you like to share?

To promote the usage of this project by more organizations, it is essential to clearly define the license agreement that this project follows. By doing so, potential users can understand the rights and permissions associated with the software. This clarity also allows organizations to confidently assess the compatibility of the license with their own projects and make informed decisions about incorporating this project into their systems.

Currently, both openim-server and openim-sdk-core rely on this project. Is it possible for this project to adopt the Apache License, just like the previous two?

Therefore, I highly recommend to explicitly state the open-source license that applies to this project.

**Comment by cubxxw** [comment]
I think it's still Apache. Thank you for your advice

**Comment by trevorwang** [comment]
Thanks for the quick response.   I would like to create a PR to add this license if you don't mind.

**Comment by cubxxw** [comment]
@trevorwang of course
