### ISSUE TITLE
[Other]: gen.cmd failed

### ISSUE THREAD

**Issue by zhaolibo1989** [openimsdk/protocol#39]
### What would you like to share?

I use `gen.cmd` to generate *.go, but get errors as follow:
```
D:\work\code\OpenIMSDK\protocol>protoc --go_out=plugins=grpc:./conversation --go_opt=module=github.com/OpenIMSDK/protocol/conversation conversation/conversation.proto
--go_out: protoc-gen-go: plugins are not supported; use 'protoc --go-grpc_out=...' to generate gRPC

See https://grpc.io/docs/languages/go/quickstart/#regenerate-grpc-code for more information.

D:\work\code\OpenIMSDK\protocol>protoc --version
libprotoc 22.0

D:\work\code\OpenIMSDK\protocol>protoc-gen-go --version
protoc-gen-go v1.29.1

D:\work\code\OpenIMSDK\protocol>protoc-gen-go-grpc --version
protoc-gen-go-grpc 1.3.0

D:\work\code\OpenIMSDK\protocol>
```

### Additional information

I use 'protoc --go-grpc_out=...' to generate gRPC, and then, failed again.
```
D:\work\code\OpenIMSDK\protocol>protoc --go-grpc_out=plugins=grpc:./conversation --go_opt=module=github.com/OpenIMSDK/protocol/conversation conversation/conversation.proto
Unknown flag: --go_opt
```

**Comment by zhaolibo1989** [comment]
I use 'protoc --go-grpc_out=...' to generate gRPC, and then, failed again.
```
D:\work\code\OpenIMSDK\protocol>protoc --go-grpc_out=plugins=grpc:./conversation --go_opt=module=github.com/OpenIMSDK/protocol/conversation conversation/conversation.proto
Unknown flag: --go_opt
```

**Comment by zhaolibo1989** [comment]
https://www.cnblogs.com/yanweifeng/p/17485496.html

**Comment by zhaolibo1989** [comment]
> https://www.cnblogs.com/yanweifeng/p/17485496.html

使用`go install github.com/golang/protobuf/protoc-gen-go`后，`protoc-gen-go`不能单独查看版本号。
```
C:\Users\Administrator>protoc-gen-go --version
protoc-gen-go: unknown argument "--version" (this program should be run by protoc, not directly)
```

生成的 *.go 中提示的 protoc-gen-go 版本有变化。
```
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0 ****这里原来是 v1.29.1
// 	protoc        v4.22.0
// source: conversation/conversation.proto
```

试图 go install 指定 v1.29.1 版本号安装时，提示没有这个版本。如何控制这个版本，原文件的 v1.29.1 版本是哪里来的？
```
C:\Users\Administrator>go install github.com/golang/protobuf/protoc-gen-go@v1.29.1
go: github.com/golang/protobuf/protoc-gen-go@v1.29.1: github.com/golang/protobuf/protoc-gen-go@v1.29.1: invalid version: unknown revision protoc-gen-go/v1.29.1
```

使用 v1.31.0 版本的 protoc-gen-go 生成的 go 文件对 protocol 的使用有什么影响？

**Comment by gch2008net** [comment]
got it

**Comment by mo3et** [comment]
I have also encountered this problem. 

I solve to use `go install github.com/golang/protobuf/protoc-gen-go`. It work it.

So anyone have this problem. You can refer to the article mentioned in the previous comment.

**Comment by mo3et** [comment]
> > https://www.cnblogs.com/yanweifeng/p/17485496.html
> 
> 使用`go install github.com/golang/protobuf/protoc-gen-go`后，`protoc-gen-go`不能单独查看版本号。
> 
> ```
> C:\Users\Administrator>protoc-gen-go --version
> protoc-gen-go: unknown argument "--version" (this program should be run by protoc, not directly)
> ```
> 
> 生成的 *.go 中提示的 protoc-gen-go 版本有变化。
> 
> ```
> // Code generated by protoc-gen-go. DO NOT EDIT.
> // versions:
> // 	protoc-gen-go v1.31.0 ****这里原来是 v1.29.1
> // 	protoc        v4.22.0
> // source: conversation/conversation.proto
> ```
> 
> 试图 go install 指定 v1.29.1 版本号安装时，提示没有这个版本。如何控制这个版本，原文件的 v1.29.1 版本是哪里来的？
> 
> ```
> C:\Users\Administrator>go install github.com/golang/protobuf/protoc-gen-go@v1.29.1
> go: github.com/golang/protobuf/protoc-gen-go@v1.29.1: github.com/golang/protobuf/protoc-gen-go@v1.29.1: invalid version: unknown revision protoc-gen-go/v1.29.1
> ```
> 
> 使用 v1.31.0 版本的 protoc-gen-go 生成的 go 文件对 protocol 的使用有什么影响？

you can find version in [here](https://pkg.go.dev/github.com/golang/protobuf?tab=versions).  also everyone package you can find in [pkg.go.dev](https://pkg.go.dev/).

So I have to answer the question. First, update `protoc-gen-go`  usually is not breaking change. It is not problem. Just use  `proto` file generate corresponding go file. So you worry the version.
